#!/usr/bin/Python3

from config import client
from config import Credentials
from config import IntegrationID


def get_rate(credentials: dict) -> dict:
    """Generates a valid rate object

    :param credentials: login credentials
    :return: GetRatesResponse object
    """

    rate_object = dict(
        FromZIPCode="11216",
        ToCountry="GB",
        ServiceType="US-PMI",
        ServiceDescription="USPS Priority Mail International",
        WeightOz=28,
        PackageType="Package",
        ShipDate="2020-08-21",
        DeclaredValue=3.98,
        ContentType="Gift"
    )

    rate = client.service.GetRates(
        Credentials=credentials,
        Rate=rate_object)

    rate["Rates"]["Rate"][0]["AddOns"] = None
    return rate["Rates"]["Rate"][0]


def create_indicium(credentials: dict, rate: dict) -> dict:
    """Creates a shipping label

    :param credentials: login credentials
    :param rate: valid rate object generated by stamps.com
    :return: CreateIndiciumResponse object
    """

    from_address = dict(
        FullName="Christopher Wallace",
        Address1="226 St. James Pl.",
        City="Brooklyn",
        State="NY",
        ZIPCode="11216",
        Country="US"
    )

    to_address = dict(
        FullName="Rowan Atkinson",
        Address1="22 Rathbone Street",
        City="London",
        PostalCode="W1T 1LA",
        Country="GB"
    )

    customs = dict(
        ContentType="Gift",
        CustomsLines=dict(
            CustomsLine=dict(
                Description="Can of Beans",
                Quantity=1,
                Value=3.98,
                WeightOz=28
            )
        )
    )
    indicium = client.service.CreateIndicium(
        Credentials=credentials,
        IntegratorTxID=IntegrationID,
        Rate=rate,
        From=from_address,
        To=to_address,
        Customs=customs
    )

    return indicium


def save_customs_form(url: str) -> None:
    """Creates a pdf file from image url

    :param url: path to image
    """
    from PIL import Image
    import requests
    from io import BytesIO

    response = requests.get(url)
    img = Image.open(BytesIO(response.content))
    rgb = Image.new('RGB', img.size, (255, 255, 255))  # white background
    rgb.paste(img, mask=img.split()[3])  # paste using alpha channel as mask
    rgb.save("../customs_form.pdf", 'PDF', resoultion=100.0)


def main():
    rate = get_rate(credentials=Credentials)

    indicium = create_indicium(
        credentials=Credentials,
        rate=rate
    )

    print(indicium)
    save_customs_form(url=indicium["URL"])


if __name__ == "__main__":
    main()
